### ISSUE TITLE
Hover magico

### ISSUE THREAD

**Issue by thiagofrancisquete** [maicolsantos/maicolsantos.github.io#1]
###### ps²: desculpe-me contata-lo por aqui, dei uma olhada no seu twitter e o ultimo tweet era de 2 meses atrás, achei que por aqui seria mais fácil de falar com você :grimacing:

**Comment by maicolsantos** [comment]
Fala Thiago blz?

Cara muito obrigado pelos elogios.

Mano foi usado js para fazer isso, aqui tem o link de onde foi tirado [Efeito Hover](http://tholman.com/image-nodes/).

Mas cara no site também foi usado [Tweenmax](https://greensock.com/), aconselho muito.

Esse site não ta mais online, agora está esse [Maicol](http://maicolsantos.com/), e foi usado Tweenmax e [Scroll Magic](http://scrollmagic.io/)

E mano, meu Twitter ta muito parado mesmo.

**Comment by thiagofrancisquete** [comment]
Valeu por compartilhar o conhecimento mano :smile: 
Vou ver o conteudo. Abraço :clap:
